#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check:format ||
(
    echo '🤢🤮 Prettier Check Failed. Run yarn run format, add changes and try commit again';
    false;
)

# Check ESLint Standards
npm run check:lint ||
(
        echo '😤👋ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. '
        false; 
)

# Check tsconfig standards
npm run check:types ||
(
    echo '❌ Failed Type check'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Committing this now....'
